# Generated by Django 3.2 on 2023-03-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_name',
            field=models.CharField(default='', max_length=254),
        ),
    ]
