# Generated by Django 3.2 on 2023-02-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_aboutme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutMe',
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['live', 'priority', '-created_on']},
        ),
        migrations.AddField(
            model_name='testimonial',
            name='about_me',
            field=models.BooleanField(default=False),
        ),
    ]
