# Generated by Django 3.2 on 2023-01-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20221230_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orientation',
            field=models.IntegerField(choices=[(1, 'Landscape'), (0, 'Portrait')], default=1),
        ),
    ]
