# Generated by Django 3.2 on 2023-01-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_orientation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='orientation',
            field=models.CharField(blank=True, choices=[('Landscape', 'Landscape'), ('Portrait', 'Portrait')], default='Landscape', max_length=9, null=True),
        ),
    ]
