# Generated by Django 3.2 on 2023-01-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_orientation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='orientation',
            field=models.CharField(blank=True, choices=[('Landscape', 'Landscape'), ('Portrait', 'Portrait'), ('N/A', 'N/A')], max_length=9, null=True),
        ),
    ]
