# Generated by Django 3.2 on 2023-01-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_orientation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='orientation',
            field=models.CharField(blank=True, choices=[('Landscape', 'Landscape'), ('Portrait', 'Portrait'), ('N/A', 'Not Applicable')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
