# Generated by Django 3.2 on 2023-01-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20230102_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highlight',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
