# Generated by Django 3.2 on 2023-01-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_unique',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
    ]
